version: '3.9'
services:
  sql-server-express:
    image: mcr.microsoft.com/mssql/server:latest
    container_name: docker-sql-server-express
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "..."
    ports:
      - "1433:1433"
    networks:
      - my-network

networks:
  my-network:
    external: true
